apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240307085128.0.0+build.6aff574
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240307085128.0.0+build.6aff574
  releaseNotes: |
    Release v20240307085128.0.0+build.6aff574 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tap-ci/ci-pipeline/apps-06-03-2024-23-20-27-779908526/where-for-dinner-my-apps-bundle@sha256:b97f94f317be93c9115192f4f6771c4a5e34599312d29d31443d3c5ba527c9ef
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

