apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search-proc.my-apps.tap.20240307085147.0.0+build.6aff574
spec:
  refName: where-for-dinner-search-proc.my-apps.tap
  version: 20240307085147.0.0+build.6aff574
  releaseNotes: |
    Release v20240307085147.0.0+build.6aff574 of package where-for-dinner-search-proc.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tap-ci/ci-pipeline/apps-06-03-2024-23-20-27-779908526/where-for-dinner-search-proc-my-apps-bundle@sha256:f32359cc64f47fe6fe7c962728bb749ca4fcbf7a0a26ac0102937e1aa6497e38
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

